language:  dart

addons:
  apt:
    packages:
      - lib32stdc++6

env:
    - PROJECT="quiz" 

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor

script:
    - cd $PROJECT
    - ../flutter/bin/flutter test    
    - cd ..

cache:
  directories:
    - $HOME/.pub-cache